version: "3"

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./web:/var/www/laravel
    depends_on:
      - mysql
      - redis

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - '8001:80'
    volumes: 
      - ./web:/var/www/laravel
    depends_on: 
      - app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0
    volumes:
      - ./docker/redis:/data
    ports:
      - '6379:6379'

  schemaspy:
    build:
      context: ./docker/schemaspy
      args:
        MYSQL_CONNECTOR_VERSION: ${MYSQL_CONNECTOR_VERSION:-8.0.33}
    container_name: schemaspy
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/schemaspy/output:/output
      - ./docker/schemaspy/schemaspy.properties:/schemaspy.properties
    depends_on:
      - mysql
    command: >
      -configFile /schemaspy.properties
