version: "3"

networks: 
  laravel:
    driver: bridge

services:
  app:
    container_name: app
    restart: always
    build:
      context: ./docker/php
      args:
        OCTANE_MAX_REQUESTS: ${OCTANE_MAX_REQUESTS:-1}
    ports:
      - '9000:9000'
    networks: 
      - laravel
    volumes:
      - ./web:/var/www/laravel
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
      - redis

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    ports:
      - '8001:80'
    networks: 
      - laravel
    volumes: 
      - ./web:/var/www/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks: 
      - laravel
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0
    restart: always
    hostname: redis
    volumes:
      - ./docker/redis:/data
    ports:
      - '6479:6479'
    networks: 
      - laravel
    command: redis-server --slaveof redis-master 6379
