name: "php artisan test"

on:
  pull_request:
    types: [opened, reopened]
  issue_comment:
    types: [created, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: "Run Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check if tests should be skipped
        id: check_skip
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ] && [ -n "${{ github.event.issue.pull_request }}" ] && [[ "${{ github.event.comment.body }}" != *"/run-tests"* ]]; then
            echo "Tests should be skipped."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Check Docker Compose services
        run: |
          services=$(docker-compose ps -q)
          for service in $services; do
            status=$(docker inspect -f '{{.State.Status}}' $service)
            if [ "$status" != "running" ]; then
              echo "Service $service is not running."
              exit 1
            fi
          done

      - name: dokcer-compose Laravel Init
        if: steps.check_skip.outcome == 'success'
        run: |
          docker compose up -d
          docker compose exec -T php-apache bash -c "composer install"
          docker compose exec -T php-apache bash -c "cp .env.example .env"
          docker compose exec -T php-apache bash -c "php artisan key:generate"
          docker compose exec -T php-apache bash -c "php artisan config:cache"
          docker compose exec -T php-apache bash -c "sleep 200"

      - name: Exec Test
        if: steps.check_skip.outcome == 'success'
        run: |
          # docker compose exec -T php-apache bash -c "phpdbg -qrr ./vendor/bin/phpunit --coverage-text --colors=never > storage/logs/coverage.log"
          # docker compose exec -T php-apache bash -c "cat storage/logs/coverage.log"
          docker compose exec -T php-apache bash -c "php artisan test --coverage-text --colors=never > storage/logs/coverage.log"
          docker compose exec -T php-apache bash -c "cat storage/logs/coverage.log"

      - name: Shut down Docker Compose
        if: always()
        run: |
          docker compose down

      - name: Cat Test Result
        if: steps.check_skip.outcome != 'success' && ${{ failure() }}
        run: |
          cat ./web/storage/logs/coverage.log

      - name: Sed Coverage Report
        if: steps.check_skip.outcome == 'success'
        run: |
          sed -E "s/"$'\E'"\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" | \
          grep "Code Coverage Report:" -A6 ./web/storage/logs/coverage.log | sed -e "s/^ *//" | sed -e "s/ *$//" | sed -e "/^ *$/d" > ./web/storage/logs/coverage-summary.log

      - name: Read coverage summary
        if: steps.check_skip.outcome == 'success'
        id: coverage-summary
        uses: juliangruber/read-file-action@v1
        with:
          path: ./web/storage/logs/coverage-summary.log

      - name: Comment Coverage Summary
        if: steps.check_skip.outcome == 'success'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage-summary
          # ref: https://zenn.dev/katzumi/articles/995df5abebc91e312167
          message: |
            ## Coverage Summary
            ${{ steps.coverage-summary.outputs.content }}
            ## Coverage Report
            ${{ steps.coverage-report-urls.outputs.content }}

      - name: Action Slack Notify
        # Pick up events even if the job fails or is canceled.
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
