name: "php artisan test"

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: "Run Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Check Docker Compose services
        run: |
          services=$(docker-compose ps -q)
          for service in $services; do
            status=$(docker inspect -f '{{.State.Status}}' $service)
            if [ "$status" != "running" ]; then
              echo "Service $service is not running."
              exit 1
            fi
          done

      - name: dokcer-compose Laravel Init
        run: |
          docker compose up -d
          docker compose exec -T php-apache bash -c "composer install"
          docker compose exec -T php-apache bash -c "cp .env.example .env"
          docker compose exec -T php-apache bash -c "php artisan key:generate"
          docker compose exec -T php-apache bash -c "php artisan config:cache"
          docker compose exec -T php-apache bash -c "sleep 200"

      - name: Exec Test
        run: |
          docker compose exec -T php-apache bash -c "php artisan test --stop-on-failure --coverage"

      - name: Shut down Docker Compose
        if: always()
        run: |
          docker compose down

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./web/coverage/coverage.xml

      # - name: Action Slack Notify
      #   # Pick up events even if the job fails or is canceled.
      #   if: always()
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": ":github: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":github: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
