on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          release-type: python
          package-name: practice-release-please-hamakou108
