on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: github
          path: ./api
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
