name: "php artisan test"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/run-tests'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: dokcer-compose Laravel Init
        run: |
          docker-compose up -d
          docker compose exec -T php-apache bash -c "composer install"
          docker compose exec -T php-apache bash -c "cp .env.example .env"
          docker compose exec -T php-apache bash -c "php artisan key:generate"
          docker compose exec -T php-apache bash -c "php artisan config:cache"
          docker compose exec -T php-apache bash -c "sleep 200"

      - name: Exec Test
        run: |
          # docker compose exec -T php-apache bash -c "phpdbg -qrr ./vendor/bin/phpunit --coverage-text --colors=never > storage/logs/coverage.log"
          # docker compose exec -T php-apache bash -c "cat storage/logs/coverage.log"
          docker compose exec -T php-apache bash -c "php artisan test --coverage-text --colors=never > storage/logs/coverage.log"
          docker compose exec -T php-apache bash -c "cat storage/logs/coverage.log"

      - name: Cat Test Result
        run: |
          cat ./web/storage/logs/coverage.log
        if: ${{ failure() }}

      - name: Sed Coverage Report
        run: |
          sed -E "s/"$'\E'"\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" | \
          grep "Code Coverage Report:" -A6 ./web/storage/logs/coverage.log | sed -e "s/^ *//" | sed -e "s/ *$//" | sed -e "/^ *$/d" > ./web/storage/logs/coverage-summary.log

      - name: Read coverage summary
        id: coverage-summary
        uses: juliangruber/read-file-action@v1
        with:
          path: ./web/storage/logs/coverage-summary.log

      - name: Comment Coverage Summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage-summary
          message: |
            ## Coverage Summary
            ${{ steps.coverage-summary.outputs.content }}

      - name: Action Slack Notify
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        if: always() # Pick up events even if the job fails or is canceled.
