name: Update CHANGELOG on PR

on:
  pull_request:
    types: [opened]
    paths:
      - './libs/**'
  workflow_dispatch:
    inputs:
      pr_title:
        type: string
        description: "PRタイトル"
        default: 'TESTタイトル'
      pr_number:
        type: string
        description: "PR番号"
        default: 'xxx'

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get list of modified projects
        id: get_projects
        run: |
          if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
            CHANGED_FILES=$(git diff --name-only origin/main)
            PROJECTS=$(echo "$CHANGED_FILES" | grep -o '^./libs/[^/]*/' | sort | uniq)
          else
            PROJECTS=$(echo "${{ github.event.pull_request.changed_files }}" | grep -o '^./libs/[^/]*/' | sort | uniq)
          fi
          echo "Projects: $PROJECTS"
          echo "::set-output name=projects::$PROJECTS"
        shell: bash

      - name: Update CHANGELOG for each project
        if: ${{ steps.get_projects.outputs.projects != '' }}
        run: |
          for PROJECT in ${{ steps.get_projects.outputs.projects }}; do
            if [[ "${{ github.event_name }}" != 'workflow_dispatch' ]]; then
              PR_TITLE="${{ github.event.pull_request.title }}"
              PR_NUMBER="${{ github.event.pull_request.number }}"
            else
              PR_TITLE="${{ inputs.pr_title }}"
              PR_NUMBER="${{ inputs.pr_number }}"
            fi
            CHANGELOG="${PROJECT}CHANGELOG"
            DATE=$(date +'%Y-%m-%d')
            ADD_CHANGE_LOG="- $PR_TITLE (#$PR_NUMBER)"

            if grep -q "^$ADD_CHANGE_LOG" $CHANGELOG; then
              continue
            fi

            if grep -q "^## $DATE" $CHANGELOG; then
              # Insert the PR information below the found date line
              LINE_NUM=$(grep -n "^## $DATE" $CHANGELOG | cut -d: -f1)
              sed -i "$((LINE_NUM + 1)) i\$ADD_CHANGE_LOG" $CHANGELOG
            else
              # Add the date and PR information at the 6th line
              sed -i "6 i\## $DATE\n$ADD_CHANGE_LOG" $CHANGELOG
            fi

            # Commit changes if not manually triggered
            if [[ "${{ github.event_name }}" != 'workflow_dispatch' ]]; then
              git add $CHANGELOG
              git commit -m "Update CHANGELOG for PR #${{ github.event.pull_request.number }} in ${PROJECT}"
            fi
          done
        shell: bash

      - name: Push changes
        if: ${{ github.event_name != 'workflow_dispatch' && steps.get_projects.outputs.projects != '' }}
        run: |
          git push origin HEAD:refs/pull/${{ github.event.pull_request.number }}/head
